### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by Kakhovka** [danielgindi/node-python-struct#12]
Hi!
Try to pack 7 symbols string:
`let data = struct.pack("<7s", ["QWERTYU"]);`
`console.log(data); // Output: <Buffer 51 57 45 52 54 59 55>`
`console.log(struct.unpack("<7s", Buffer.from(data, "utf8"))); // Output: [ 'QWERTY' ]` 

But something goes wrong.  After unpack I get only "QWERTY" (the last character is lost)
Nodejs v11.15.0

**Comment by danielgindi** [comment]
Fixed! Thank you

**Comment by Kakhovka** [comment]
Another incorrect output:

`let int = 6754300000;`
`let data = struct.pack("<q", int);`
`console.log(data); // Output: <Buffer 60 70 96 92 ff ff ff ff>`
`let arr = struct.unpack("<q", Buffer.from(data, "utf8"));`
`console.log(arr[0].toString()); // Output: -1835634592`

Nodejs v11.15.0

**Comment by danielgindi** [comment]
Fixed in 1.1.1
