### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by Kakhovka** [danielgindi/node-python-struct#13]
`let int = 6754300000;`
`let data = struct.pack("<q", int);`
`console.log(data); // Output: <Buffer 60 70 96 92 ff ff ff ff>`
`let arr = struct.unpack("<q", Buffer.from(data, "utf8"));`
`console.log(arr[0].toString()); // Output: -1835634592` !!!!!!???? :)

Nodejs v11.15.0

**Comment by danielgindi** [comment]
Fixed in 1.1.1.
This was due to a difference in `Long.toInt` behavior, now using the newer methods
