### ISSUE TITLE
String write encoding is incorrect

### ISSUE THREAD

**Issue by xlpxxx** [danielgindi/node-python-struct#14]
struct.pack('16s',  [newToken]);
> Here should write ascii encoding instead of utf-8 encoding

Format 16s or 16c, should receive input buffer type

eg:
```
    if (newToken instanceof Array || newToken instanceof Buffer) {
        newToken = String.fromCharCode.apply(null, newToken);
    }
    struct.pack('16s',  [newToken]);
```

**Comment by xlpxxx** [comment]
It is recommended to set the s and p formats to ascii and utf-8 respectively. Currently I can only use c code instead of s to write ascii format.

struct.pack('16s',  [newToken]);

struct.pack('16b',  [ ...newToken]);

**Comment by danielgindi** [comment]
AFAIK it *is* supposed to automatically encode unicode strings as UTF-8, see [Python issue](https://bugs.python.org/issue10783).

We could add an "encoding" argument if necessary.
