### ISSUE TITLE
RangeError with x in format

### ISSUE THREAD

**Issue by MrScruffyish** [danielgindi/node-python-struct#4]
(I've already sent you an email about this, but I add this as an issue in case someone else finds it).

This code fails (using node 6.9.2)

```
var pystruct = require('python-struct');
format = '<3s6x3s';
size = pystruct.sizeOf(format);
data = pystruct.pack(format, ['FOO','BAR'] );
```
with
```
buffer.js:690
    throw new RangeError('Out of range index');
```

It seems to do a division by zero when calculating the size and the sizeOf command returns NaN.

**Comment by danielgindi** [comment]
Thanks for your report!
This was due to a bug in the little-endian mapping object, which had "0" alignment operators - and caused division by zero.
They should be 1, and were changed in the past in the other mapping objects and missed this one.

It is fixed now in 1.0.5
